namespace PacketParser.FileTransfer {
    public enum FileStreamTypes {
        //FtpActiveRetr,
        //FtpActiveStor,
        //FtpPassiveRetr,
        //FtpPassiveStor,
        BackConnect,
        FTP,
        HttpGetChunked,
        HttpGetNormal,
        HttpPost,
        HttpPostMimeMultipartFormData,
        HttpPostMimeFileData,
        HttpPostUpload,
        HTTP2,
        IEC104,
        IMAP,
        LPD,
        Meterpreter,
        njRAT,
        OscarFileTransfer,
        POP3,
        RTP,
        SMB,
        SMB2,
        SMTP,
        TFTP,
        TlsCertificate,
        VNC,//RFB = Remote Frame Buffer
    }
}